### ISSUE TITLE
Decide on target browsers

### ISSUE THREAD

**Issue by bencmbrook** [transcend-io/conflux#13]
From Jimmy:

> I would be down for not using any compiler also. But it also depends on target support.
> 
> I'm not a big fan of using TypeScript...
> 
> Yes, zip streamer would be a bottleneck. But so was the "old" original zip streamer I wrote also. Not sure if it would be any befit to use concurrency, you have to write the zip entries in order

> You could always fetch 2 resources and get the response.body 
> Then you would already have started the download. 
> 
> What would you say if set the lowest targeted support to be browser that has support for import?
> - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
> - https://caniuse.com/#feat=es6-module-dynamic-import
> 
> Helping the hole community to push for a more "evergreen" browser.
> This is the time to do so when http2 have gotten a wider support
> Good for lazy loading also 
> 
> <blockquote><img src="https://developer.mozilla.org/static/img/opengraph-logo.72382e605ce3.png" width="48" align="right"><div>MDN Web Docs</div><div><strong><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import">import</a></strong></div><div>The static import statement is used to import bindings which are exported by another module.</div></blockquote>
> 
> _Originally posted by @jimmywarting in https://github.com/transcend-io/conflux/issues/2#issuecomment-508162681_

**Comment by bencmbrook** [comment]
Regarding target support, import feels aggressive (FF only supported it last month). For this to be widely useful we should have better support. 

Maybe we match StreamSaver.js since it’s a likely pairing? 

I can set up Babel and Webpack if we want it.

**Comment by eligrey** [comment]
+1 for TypeScript with Babel, but normal ES8 with Babel is also okay if @jimmywarting isn't comfortable with TypeScript.

**Comment by jimmywarting** [comment]
> Maybe we match StreamSaver.js since it’s a likely pairing?
👍 

> I can set up Babel and Webpack if we want it.

Could you hold of with that for a moment? Working on the core bone of the lib now setting up some base stuff from https://github.com/transcend-io/conflux/issues/2#issuecomment-508059274 and then we can take it from there just to get some lift off 🚀 

> but normal ES8 with Babel is also okay if @jimmywarting isn't comfortable with TypeScript.
That would make me happy then i perhaps could use module import directly without having to transpile the file at all.

Like working with cuting edge browser and just run the script as it's and when it's time for release then i build/compile and minify scripts

**Comment by bencmbrook** [comment]
FWIW when I was toying with this last month, I wrote some types for @jimmywarting's code

```ts
/* global ReadableStream */

type TypedArray = Int8Array | Uint8Array | Int16Array | Uint16Array | Int32Array | Uint32Array | Uint8ClampedArray | Float32Array | Float64Array;


/**
 * 32-bit cyclic redundancy check, or CRC-32 - checksum
 */
class Crc32 {
  crc: number;
  table: any;
  constructor () {
    this.crc = -1;
  }

  append(data: TypedArray) {
    let crc = this.crc | 0;
    const table = this.table;
    for (var offset = 0, len = data.length | 0; offset < len; offset++) {
      crc = (crc >>> 8) ^ table[(crc ^ data[offset]) & 0xFF];
    }
    this.crc = crc;
  }

  get () {
    return ~this.crc;
  }
}

Crc32.prototype.table = (() => {
  let i
  let j
  let t;
  let table = [];

  for (i = 0; i < 256; i++) {
    t = i;
    for (j = 0; j < 8; j++) {
      t = (t & 1)
        ? (t >>> 1) ^ 0xEDB88320
        : t >>> 1;
    }
    table[i] = t;
  }
  return table
})()


type DataHelper = {
  array: Uint8Array,
  view: DataView,
}

const getDataHelper = (byteLength: number): DataHelper => {
  var uint8 = new Uint8Array(byteLength)
  return {
    array: uint8,
    view: new DataView(uint8.buffer)
  };
}

type FileLike = File & {
  directory: string,
  comment: string,
  stream(): ReadableStream,
}

type ZipObj = {
  crc?: Crc32,
  uncompressedLength: number,
  compressedLength: number,
  ctrl: ReadableStreamDefaultController,
  writeFooter: Function,
  writeHeader: Function,
  reader?: ReadableStreamDefaultReader,
  offset: number
  header?: DataHelper,
  fileLike: FileLike,
  level: number,
  directory: boolean,
}

const pump = (zipObj: ZipObj) => zipObj.reader ? zipObj.reader.read().then(chunk => {
  if (zipObj.crc) {
    if (chunk.done) return zipObj.writeFooter();
    const outputData = chunk.value;
    zipObj.crc.append(outputData);
    zipObj.uncompressedLength += outputData.length;
    zipObj.compressedLength += outputData.length;
    zipObj.ctrl.enqueue(outputData);
  } else {
    throw new Error('Missing zipObj.crc');
  }
}) : undefined;

export function ZIP(underlyingSource: UnderlyingSource) {
  const files = Object.create(null);
  const filenames: string[] = [];
  const encoder = new TextEncoder();
  let offset = 0;
  let activeZipIndex = 0;
  let ctrl: ReadableStreamDefaultController;
  let activeZipObject: ZipObj;
  let closed: boolean;

  function next () {
    activeZipIndex++;
    activeZipObject = files[filenames[activeZipIndex]];
    if (activeZipObject) processNextChunk();
    else if (closed) closeZip();
  }
  
  const zipWriter: ReadableStreamDefaultController = {
    desiredSize: null,

    error(err) {
      console.error(err)
    },

    enqueue(fileLike: FileLike) {
      if (closed) throw new TypeError('Cannot enqueue a chunk into a readable stream that is closed or has been requested to be closed');

      let name = fileLike.name.trim();
      const date = new Date(typeof fileLike.lastModified === 'undefined' ? Date.now() : fileLike.lastModified);

      if (fileLike.directory && !name.endsWith('/')) name += '/';
      if (files[name]) throw new Error('File already exists.');

      const nameBuf = encoder.encode(name);
      filenames.push(name);

      const zipObject: ZipObj = files[name] = {
        level: 0,
        ctrl,
        directory: !!fileLike.directory,
        nameBuf,
        comment: encoder.encode(fileLike.comment || ''),
        compressedLength: 0,
        uncompressedLength: 0,
        offset,

        writeHeader () {
          const header = getDataHelper(26)
          const data = getDataHelper(30 + nameBuf.length)

          zipObject.offset = offset;
          zipObject.header = header;

          if (zipObject.level !== 0 && !zipObject.directory) {
            header.view.setUint16(4, 0x0800);
          }

          header.view.setUint32(0, 0x14000808);
          header.view.setUint16(6, (((date.getHours() << 6) | date.getMinutes()) << 5) | date.getSeconds() / 2, true);
          header.view.setUint16(8, ((((date.getFullYear() - 1980) << 4) | (date.getMonth() + 1)) << 5) | date.getDate(), true);
          header.view.setUint16(22, nameBuf.length, true);
          data.view.setUint32(0, 0x504b0304);
          data.array.set(header.array, 4);
          data.array.set(nameBuf, 30);
          offset += data.array.length;
          ctrl.enqueue(data.array);
        },

        writeFooter () {
          const footer = getDataHelper(16);
          footer.view.setUint32(0, 0x504b0708);

          if (zipObject.crc && zipObject.header) {
            zipObject.header.view.setUint32(10, zipObject.crc.get(), true);
            zipObject.header.view.setUint32(14, zipObject.compressedLength, true);
            zipObject.header.view.setUint32(18, zipObject.uncompressedLength, true);
            footer.view.setUint32(4, zipObject.crc.get(), true);
            footer.view.setUint32(8, zipObject.compressedLength, true);
            footer.view.setUint32(12, zipObject.uncompressedLength, true);
          }

          ctrl.enqueue(footer.array);
          offset += zipObject.compressedLength + 16;
          next()
        },
        fileLike,
      }

      if (!activeZipObject) {
        activeZipObject = zipObject;
        processNextChunk();
      }
    },

    close () {
      if (closed) throw new TypeError('Cannot close a readable stream that has already been requested to be closed');
      if (!activeZipObject) closeZip();
      closed = true;
    }
  }

  function closeZip () {
    let length = 0;
    let index = 0
    let indexFilename;
    let file;

    for (indexFilename = 0; indexFilename < filenames.length; indexFilename++) {
      file = files[filenames[indexFilename]];
      length += 46 + file.nameBuf.length + file.comment.length;
    }
    const data = getDataHelper(length + 22)
    for (indexFilename = 0; indexFilename < filenames.length; indexFilename++) {
      file = files[filenames[indexFilename]];
      data.view.setUint32(index, 0x504b0102);
      data.view.setUint16(index + 4, 0x1400);
      data.array.set(file.header.array, index + 6);
      data.view.setUint16(index + 32, file.comment.length, true);
      if (file.directory) {
        data.view.setUint8(index + 38, 0x10);
      }
      data.view.setUint32(index + 42, file.offset, true);
      data.array.set(file.nameBuf, index + 46);
      data.array.set(file.comment, index + 46 + file.nameBuf.length);
      index += 46 + file.nameBuf.length + file.comment.length;
    }
    data.view.setUint32(index, 0x504b0506);
    data.view.setUint16(index + 8, filenames.length, true);
    data.view.setUint16(index + 10, filenames.length, true);
    data.view.setUint32(index + 12, length, true);
    data.view.setUint32(index + 16, offset, true);
    ctrl.enqueue(data.array);
    ctrl.close();
  }

  function processNextChunk () {
    if (!activeZipObject) return;
    if (activeZipObject.reader) return pump(activeZipObject);
    if (activeZipObject.fileLike.stream) {
      activeZipObject.crc = new Crc32();
      activeZipObject.reader = activeZipObject.fileLike.stream().getReader();
      activeZipObject.writeHeader();
    } else next();
  }

  return new ReadableStream({
    start: c => {
      ctrl = c;
      underlyingSource.start && Promise.resolve(underlyingSource.start(zipWriter));
    },
    pull () {
      return processNextChunk() || (
        underlyingSource.pull &&
        Promise.resolve(underlyingSource.pull(zipWriter))
      )
    },
  });
}
```

**Comment by jimmywarting** [comment]
how about having a `d.ts` file? i would be fine with that.

**Comment by bencmbrook** [comment]
works for me. @eligrey?

**Comment by eligrey** [comment]
@bencmbrook @jimmywarting I'm fine with a separate `d.ts` file for types.

**Comment by jimmywarting** [comment]
StreamSaver don't use any compiler like babel or such.
I think the most adv feature it uses are Spread operators & Arrow fn
It isn't service worker, or streams since it now fallbacks to using a blob builder and opening up that like FileSaver.js dose. 

I haven't tried many browser. So i don't know what the lowest supported browser support is.
Would be nice to have some continues testing on commits that test different browsers. But instead of saving it to the disc I would tamper with the streamsaver.js to use ajax to use xhr to get the file instead of opening up the download link

**Comment by jimmywarting** [comment]
Web stream pollyfill is also one of the requirements.

From the looks of it it seems like they are going for `class F extends ReadableStream {}`

https://github.com/MattiasBuelens/web-streams-polyfill/issues/20

**Comment by jimmywarting** [comment]
| Api                | Chrome | Edge | Firefox | IE | Opera | Safari |
|--------------------|--------|-----:|---------|----|-------|--------|
| classes            | 49     | 13   | 45      | x  | 36    | 9      |
| script[module]     | 61     | 16   | 60      | x  | 48    | 10.1   |
| [spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility)             |        |      |         |    |       |        |
| Service Worker     | 45     | 17   | 44      | x  | 32    | 11.3   |
| StreamSaver.js     | ?      | ?    | ?       | ?  | ?     | ?      |
| WebStreamPollyfill | ?      | ?    | ?       | ?  | ?     | ?      |
| conflux            | ?      | ?    | ?       | ?  | ?     | ?      |
|             |        |      |         |    |       |        |
|                    |        |      |         |    |       |        |

**Comment by jimmywarting** [comment]
When dealing with zip64 then we need to deal with larger numbers, there is 
 [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) and other libs that you can use that also handles big numbers for ya, like https://github.com/GoogleChromeLabs/jsbi for example
