### ISSUE TITLE
Write some test

### ISSUE THREAD

**Issue by jimmywarting** [transcend-io/conflux#3]
Recommend using [tape](https://www.npmjs.com/package/tape) but are open for suggestions.

Would be easier to run test in node instead of the browser.
so perhaps use node + [web-streams-polyfill](https://github.com/MattiasBuelens/web-streams-polyfill)?
Unless we have to use web worker to test something in wish case i recommend headless chrome [puppeteer](https://github.com/GoogleChrome/puppeteer)

**Comment by jimmywarting** [comment]
Also recommend that we hook it into things like Trravis CI or similar?

**Comment by bencmbrook** [comment]
@jimmywarting yeah we can run definitely run CI on Transcend's Travis organization. I recommend we protect `master` and only PR into it from feature branches, where CI must pass before merge.

I'm agnostic on test frameworks and defer to @eligrey - I'm personally most familiar with Mocha and [Ava](https://github.com/avajs/ava), which is similar to tape.

**Comment by bencmbrook** [comment]
Ava also has built in support for code coverage (https://github.com/transcend-io/conflux/issues/5)

**Comment by eligrey** [comment]
I'm also fine with Ava.

**Comment by jimmywarting** [comment]
Never tried Ava before but fine with me.
oh, since we are going to bench test other zip libs it makes more since to run the test in a browser

**Comment by bencmbrook** [comment]
I’d be fine with splitting out testing and benchmarking. I think the test framework could get messy if we’re trying to use puppeteer etc for simple unit tests.

**Comment by jimmywarting** [comment]
ok...

**Comment by eligrey** [comment]
I'm fine with splitting both and don't mind if we re-use ava.li for benchmarking as well.

**Comment by bencmbrook** [comment]
If we really want to run tests in a browser, we could use Karma. It doesn't play _that_ nicely with Ava (best with Jasmine), but it does have a [Benchmark.js integration](https://github.com/JamieMason/karma-benchmark)
- https://github.com/karma-runner/karma
- https://github.com/karma-runner/karma-chrome-launcher

How much do we want to run our tests in the browser versus Node?

**Comment by jimmywarting** [comment]
Karma benchmark looks promising

> How much do we want to run our tests in the browser versus Node?

Is there any point in running some test in node?

**Comment by jimmywarting** [comment]
just putting it out there: tape + [airtap](https://github.com/airtap/airtap)

tape is similar to Ava, airtap makes it work in browsers.
have worked with it quite much, specially together with webtorrent

**Comment by eligrey** [comment]
tape + airtap sounds good to me!

**Comment by jimmywarting** [comment]
Created two utility functions that may come in handy when writing test

- sha1 hex from typed array
```js
/**
 * takes a typed array and returns a hex string
 *
 * @param  {ArrayBuffer|ArrayBufferView} arr
 * @return {promise<string>}
 */
async function sha1(arr) {
  const hash = await crypto.subtle.digest('sha-1', arr);
  const uint8 = new Uint8Array(hash);
  return uint8.reduce((memo, byte) =>
    memo + (byte < 16 ? '0' : '') + byte.toString(16)
  , '');
}
```
Alternativ is to add [simple-sha1](https://www.npmjs.com/package/simple-sha1) as a devDependency 

- A manual stream to arrayBuffer builder
```js
/**
 * A manual `new Response(response).arrayBuffer()`
 * fetch can't read a polyfilled ReadableStream.
 * https://github.com/MattiasBuelens/web-streams-polyfill/issues/20
 *
 * @param  {ReadableStream} readable
 * @return {promise<ArrayBuffer>}
 */
async function arrayBufferFromStream(readable) {
  let size = 0;
  let offset = 0;
  const chunks = [];

  for await (chunk of readable) {
    chunks.push(it.value);
    size += it.value.length;
  }

  const uint8 = new Uint8Array(size);

  for (let chunk of chunks) {
    uint8.set(chunk, offset);
    offset += chunk.length;
  }

  return uint8.buffer;
}
```

**Comment by jimmywarting** [comment]
to help out a bit here is the simple chechsum test test we could start out with.

```js
test('zip checksum', async (t) => {
  const { readable, writable } = new Something();
  const writer = writable.getWriter();

  writer.write({
    name: '/cat.txt',
    lastModified: new Date(0),
    stream: () => new Response('mjau').body,
  });

  writer.close();

  const hash = await sha1(arrayBufferFromStream(readable));

  t.equal(hash, '28d2f86c3dfbda4022aa59bad3aca52030a7aa52');
});
```

uncertain how we manage to the zip writer into the test when it uses `import`...
got any ideas?

**Comment by jimmywarting** [comment]
thinking we should create a folder for test

```
╔conflux
╠═══test
║...╠═══fixture
║...║...╠═══index.js (a dictonary to list/load all fixtures)
║...║...╠═══cat.zip
║...║...╚═══cat.jpg
╠...║═══index.js (all test)
╠...║═══util.js (helper functions to write test)
```

**Comment by eligrey** [comment]
@jimmywarting That folder structure works for me
