### ISSUE TITLE
Dn is not a function

### ISSUE THREAD

**Issue by sebastiaoLa** [transcend-io/conflux#76]
i'm using requireJs on the browser and when i do 

`
require(['https://cdn.jsdelivr.net/npm/@transcend-io/conflux@3'])
`

It raises an error
Uncaught TypeError: Dn is not a function conflux@3:1:296

Am i missing a dependency?

**Comment by bencmbrook** [comment]
Thanks for reporting @sebastiaoLa. This is addressed in #83 

btw, if you're using Node, this is only targeted at browsers, so you may run into some other issues there.
