### ISSUE TITLE
multibyte file names are garbled on Windows

### ISSUE THREAD

**Issue by Yama-Tomo** [transcend-io/conflux#86]
Hi ✋ 

When I use this package on Windows, multibyte file names are garbled. 
This is because I'm Japanese and Windows uses Shift JIS encoding.
Are there any plans to support encodings other than utf8?

**Comment by eligrey** [comment]
Are you experiencing this issue with the built-in ZIP reader in Windows? Additionally, are you also experiencing this with any third party ZIP readers?

**Comment by Yama-Tomo** [comment]
sorry.. 🙏 
I was using a third party software that does not support utf8.
There is no problem if you use the built-in software in windows.

Thank you!
